{"name": "Безуспешное сложение с лишними параметрами", "status": "broken", "statusDetails": {"message": "pydantic_core._pydantic_core.ValidationError: 1 validation error for ServerError\nstatusMessage\n  Field required [type=missing, input_value={'statusCode': 0, 'result': 7}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.8/v/missing", "trace": "self = <tests.calculator_api.test_addition.TestAddition object at 0x00000276A4405A00>\ncalculator_steps = <steps.calculator_api.calculator_steps.CalculatorSteps object at 0x00000276A5480C20>\n\n    @allure.title('Безуспешное сложение с лишними параметрами')\n    def test_unsuccessful_addition_with_extra_numbers(self, calculator_steps):\n        extra_operands = ExtraOperands(x=5, y=2, z=1)\n    \n        response = calculator_steps.do_addition(extra_operands)\n    \n        # assert_http_status_code(response=response, expected_code=422)\n        assert_json_header(response=response)\n    \n>       error = ServerSchemasSteps.get_server_error(response)\n\ntests\\calculator_api\\test_addition.py:93: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncls = <class 'steps.server_api.server_schemas_steps.ServerSchemasSteps'>, response = <Response [200 OK]>\n\n    @classmethod\n    @allure.step('Получить ошибку сервера из ответа')\n    def get_server_error(cls, response: Response) -> ServerError:\n>       return ServerError.model_validate(response.json())\nE       pydantic_core._pydantic_core.ValidationError: 1 validation error for ServerError\nE       statusMessage\nE         Field required [type=missing, input_value={'statusCode': 0, 'result': 7}, input_type=dict]\nE           For further information visit https://errors.pydantic.dev/2.8/v/missing\n\nsteps\\server_api\\server_schemas_steps.py:49: ValidationError"}, "steps": [{"name": "Выполнить сложение чисел", "status": "passed", "steps": [{"name": "Сложение x и y", "status": "passed", "steps": [{"name": "Отправка \"'POST'\" запроса на \"'/addition'\"", "status": "passed", "parameters": [{"name": "method", "value": "'POST'"}, {"name": "url", "value": "'/addition'"}, {"name": "content", "value": "None"}, {"name": "data", "value": "None"}, {"name": "files", "value": "None"}, {"name": "json", "value": "{'x': 5, 'y': 2, 'z': 1}"}, {"name": "params", "value": "None"}, {"name": "headers", "value": "None"}, {"name": "cookies", "value": "None"}, {"name": "auth", "value": "<httpx._client.UseClientDefault object at 0x00000276A3624C20>"}, {"name": "follow_redirects", "value": "<httpx._client.UseClientDefault object at 0x00000276A3624C20>"}, {"name": "timeout", "value": "<httpx._client.UseClientDefault object at 0x00000276A3624C20>"}, {"name": "extensions", "value": "None"}], "start": 1723569763524, "stop": 1723569763539}], "parameters": [{"name": "operands_payload", "value": "{'x': 5, 'y': 2, 'z': 1}"}], "start": 1723569763524, "stop": 1723569763539}], "parameters": [{"name": "operands", "value": "ExtraOperands(x=5, y=2, z=1)"}], "start": 1723569763524, "stop": 1723569763539}, {"name": "Получить ошибку сервера из ответа", "status": "broken", "statusDetails": {"message": "pydantic_core._pydantic_core.ValidationError: 1 validation error for ServerError\nstatusMessage\n  Field required [type=missing, input_value={'statusCode': 0, 'result': 7}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.8/v/missing\n", "trace": "  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\steps\\server_api\\server_schemas_steps.py\", line 49, in get_server_error\n    return ServerError.model_validate(response.json())\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\pydantic\\main.py\", line 568, in model_validate\n    return cls.__pydantic_validator__.validate_python(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "parameters": [{"name": "response", "value": "<Response [200 OK]>"}], "start": 1723569763539, "stop": 1723569763539}], "start": 1723569763524, "stop": 1723569763539, "uuid": "54a26d80-6fdb-450e-91a6-e0fd7729d63b", "historyId": "db9362465f0ab3cfff4d931bd922d0c6", "testCaseId": "db9362465f0ab3cfff4d931bd922d0c6", "fullName": "tests.calculator_api.test_addition.TestAddition#test_unsuccessful_addition_with_extra_numbers", "labels": [{"name": "story", "value": "Сложение"}, {"name": "epic", "value": "Калькулятор"}, {"name": "feature", "value": "Вычисления калькулятора"}, {"name": "parentSuite", "value": "tests.calculator_api"}, {"name": "suite", "value": "test_addition"}, {"name": "subSuite", "value": "TestAddition"}, {"name": "host", "value": "DESKTOP-QQNQKOJ"}, {"name": "thread", "value": "11904-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.calculator_api.test_addition"}]}