{"name": "Безуспешное вычисление остатка от деления с нецелочисленным числом", "status": "broken", "statusDetails": {"message": "httpx.RemoteProtocolError: Server disconnected without sending a response.", "trace": "@contextlib.contextmanager\n    def map_httpcore_exceptions() -> typing.Iterator[None]:\n        try:\n>           yield\n\nvenv\\Lib\\site-packages\\httpx\\_transports\\default.py:69: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nvenv\\Lib\\site-packages\\httpx\\_transports\\default.py:233: in handle_request\n    resp = self._pool.handle_request(req)\nvenv\\Lib\\site-packages\\httpcore\\_sync\\connection_pool.py:216: in handle_request\n    raise exc from None\nvenv\\Lib\\site-packages\\httpcore\\_sync\\connection_pool.py:196: in handle_request\n    response = connection.handle_request(\nvenv\\Lib\\site-packages\\httpcore\\_sync\\connection.py:101: in handle_request\n    return self._connection.handle_request(request)\nvenv\\Lib\\site-packages\\httpcore\\_sync\\http11.py:143: in handle_request\n    raise exc\nvenv\\Lib\\site-packages\\httpcore\\_sync\\http11.py:113: in handle_request\n    ) = self._receive_response_headers(**kwargs)\nvenv\\Lib\\site-packages\\httpcore\\_sync\\http11.py:186: in _receive_response_headers\n    event = self._receive_event(timeout=timeout)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <HTTP11Connection ['http://127.0.0.1:17678', CLOSED, Request Count: 1]>, timeout = 5.0\n\n    def _receive_event(\n        self, timeout: Optional[float] = None\n    ) -> Union[h11.Event, Type[h11.PAUSED]]:\n        while True:\n            with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):\n                event = self._h11_state.next_event()\n    \n            if event is h11.NEED_DATA:\n                data = self._network_stream.read(\n                    self.READ_NUM_BYTES, timeout=timeout\n                )\n    \n                # If we feed this case through h11 we'll raise an exception like:\n                #\n                #     httpcore.RemoteProtocolError: can't handle event type\n                #     ConnectionClosed when role=SERVER and state=SEND_RESPONSE\n                #\n                # Which is accurate, but not very informative from an end-user\n                # perspective. Instead we handle this case distinctly and treat\n                # it as a ConnectError.\n                if data == b\"\" and self._h11_state.their_state == h11.SEND_RESPONSE:\n                    msg = \"Server disconnected without sending a response.\"\n>                   raise RemoteProtocolError(msg)\nE                   httpcore.RemoteProtocolError: Server disconnected without sending a response.\n\nvenv\\Lib\\site-packages\\httpcore\\_sync\\http11.py:238: RemoteProtocolError\n\nThe above exception was the direct cause of the following exception:\n\nself = <tests.calculator_api.test_remainder.TestRemainder object at 0x00000276A4353710>\ncalculator_steps = <steps.calculator_api.calculator_steps.CalculatorSteps object at 0x00000276A5480C20>, operands = AnyOperands(x='best', y='test')\n\n    @allure.title('Безуспешное вычисление остатка от деления с нецелочисленным числом')\n    @pytest.mark.parametrize(\"operands\",\n                             CalculatorDataProvider.get_unsuccessful_not_int_data(),\n                             ids=idfn)\n    def test_unsuccessful_remainder_not_int_number(self, calculator_steps, operands: AnyOperands):\n>       response = calculator_steps.do_remainder(operands)\n\ntests\\calculator_api\\test_remainder.py:53: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nsteps\\calculator_api\\calculator_steps.py:71: in do_remainder\n    return self.calculator_api.remainder(operands.model_dump())\napi\\calculator\\calculator_api.py:72: in remainder\n    return self.api_client.post(calculator_routes_settings.remainder, json=operands_payload)\nvenv\\Lib\\site-packages\\httpx\\_client.py:1145: in post\n    return self.request(\napi\\client\\api_client.py:25: in request\n    return super().request(method, url, **kwargs)\nvenv\\Lib\\site-packages\\httpx\\_client.py:827: in request\n    return self.send(request, auth=auth, follow_redirects=follow_redirects)\nvenv\\Lib\\site-packages\\httpx\\_client.py:914: in send\n    response = self._send_handling_auth(\nvenv\\Lib\\site-packages\\httpx\\_client.py:942: in _send_handling_auth\n    response = self._send_handling_redirects(\nvenv\\Lib\\site-packages\\httpx\\_client.py:979: in _send_handling_redirects\n    response = self._send_single_request(request)\nvenv\\Lib\\site-packages\\httpx\\_client.py:1015: in _send_single_request\n    response = transport.handle_request(request)\nvenv\\Lib\\site-packages\\httpx\\_transports\\default.py:232: in handle_request\n    with map_httpcore_exceptions():\nC:\\Users\\Арсений\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\contextlib.py:158: in __exit__\n    self.gen.throw(value)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    @contextlib.contextmanager\n    def map_httpcore_exceptions() -> typing.Iterator[None]:\n        try:\n            yield\n        except Exception as exc:\n            mapped_exc = None\n    \n            for from_exc, to_exc in HTTPCORE_EXC_MAP.items():\n                if not isinstance(exc, from_exc):\n                    continue\n                # We want to map to the most specific exception we can find.\n                # Eg if `exc` is an `httpcore.ReadTimeout`, we want to map to\n                # `httpx.ReadTimeout`, not just `httpx.TimeoutException`.\n                if mapped_exc is None or issubclass(to_exc, mapped_exc):\n                    mapped_exc = to_exc\n    \n            if mapped_exc is None:  # pragma: no cover\n                raise\n    \n            message = str(exc)\n>           raise mapped_exc(message) from exc\nE           httpx.RemoteProtocolError: Server disconnected without sending a response.\n\nvenv\\Lib\\site-packages\\httpx\\_transports\\default.py:86: RemoteProtocolError"}, "steps": [{"name": "Посчитать остаток от деления чисел", "status": "broken", "statusDetails": {"message": "httpx.RemoteProtocolError: Server disconnected without sending a response.\n", "trace": "  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\steps\\calculator_api\\calculator_steps.py\", line 71, in do_remainder\n    return self.calculator_api.remainder(operands.model_dump())\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\api\\calculator\\calculator_api.py\", line 72, in remainder\n    return self.api_client.post(calculator_routes_settings.remainder, json=operands_payload)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 1145, in post\n    return self.request(\n           ^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\api\\client\\api_client.py\", line 25, in request\n    return super().request(method, url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 827, in request\n    return self.send(request, auth=auth, follow_redirects=follow_redirects)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 914, in send\n    response = self._send_handling_auth(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 942, in _send_handling_auth\n    response = self._send_handling_redirects(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 979, in _send_handling_redirects\n    response = self._send_single_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 1015, in _send_single_request\n    response = transport.handle_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 232, in handle_request\n    with map_httpcore_exceptions():\n  File \"C:\\Users\\Арсений\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\contextlib.py\", line 158, in __exit__\n    self.gen.throw(value)\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 86, in map_httpcore_exceptions\n    raise mapped_exc(message) from exc\n"}, "steps": [{"name": "Остаток от деления x на y", "status": "broken", "statusDetails": {"message": "httpx.RemoteProtocolError: Server disconnected without sending a response.\n", "trace": "  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\api\\calculator\\calculator_api.py\", line 72, in remainder\n    return self.api_client.post(calculator_routes_settings.remainder, json=operands_payload)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 1145, in post\n    return self.request(\n           ^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\api\\client\\api_client.py\", line 25, in request\n    return super().request(method, url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 827, in request\n    return self.send(request, auth=auth, follow_redirects=follow_redirects)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 914, in send\n    response = self._send_handling_auth(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 942, in _send_handling_auth\n    response = self._send_handling_redirects(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 979, in _send_handling_redirects\n    response = self._send_single_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 1015, in _send_single_request\n    response = transport.handle_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 232, in handle_request\n    with map_httpcore_exceptions():\n  File \"C:\\Users\\Арсений\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\contextlib.py\", line 158, in __exit__\n    self.gen.throw(value)\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 86, in map_httpcore_exceptions\n    raise mapped_exc(message) from exc\n"}, "steps": [{"name": "Отправка \"'POST'\" запроса на \"'/remainder'\"", "status": "broken", "statusDetails": {"message": "httpx.RemoteProtocolError: Server disconnected without sending a response.\n", "trace": "  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\api\\client\\api_client.py\", line 25, in request\n    return super().request(method, url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 827, in request\n    return self.send(request, auth=auth, follow_redirects=follow_redirects)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 914, in send\n    response = self._send_handling_auth(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 942, in _send_handling_auth\n    response = self._send_handling_redirects(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 979, in _send_handling_redirects\n    response = self._send_single_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 1015, in _send_single_request\n    response = transport.handle_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 232, in handle_request\n    with map_httpcore_exceptions():\n  File \"C:\\Users\\Арсений\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\contextlib.py\", line 158, in __exit__\n    self.gen.throw(value)\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 86, in map_httpcore_exceptions\n    raise mapped_exc(message) from exc\n"}, "parameters": [{"name": "method", "value": "'POST'"}, {"name": "url", "value": "'/remainder'"}, {"name": "content", "value": "None"}, {"name": "data", "value": "None"}, {"name": "files", "value": "None"}, {"name": "json", "value": "{'x': 'best', 'y': 'test'}"}, {"name": "params", "value": "None"}, {"name": "headers", "value": "None"}, {"name": "cookies", "value": "None"}, {"name": "auth", "value": "<httpx._client.UseClientDefault object at 0x00000276A3624C20>"}, {"name": "follow_redirects", "value": "<httpx._client.UseClientDefault object at 0x00000276A3624C20>"}, {"name": "timeout", "value": "<httpx._client.UseClientDefault object at 0x00000276A3624C20>"}, {"name": "extensions", "value": "None"}], "start": 1723569765836, "stop": 1723569765852}], "parameters": [{"name": "operands_payload", "value": "{'x': 'best', 'y': 'test'}"}], "start": 1723569765836, "stop": 1723569765852}], "parameters": [{"name": "operands", "value": "AnyOperands(x='best', y='test')"}], "start": 1723569765836, "stop": 1723569765852}], "parameters": [{"name": "operands", "value": "AnyOperands(x='best', y='test')"}], "start": 1723569765836, "stop": 1723569765852, "uuid": "b1956325-bf44-4061-90da-0120ec798f7c", "historyId": "7cb797b03b3e2a3fca2e3b3ea58381bf", "testCaseId": "e01d3943ce344354af9cd2c0d12f36dc", "fullName": "tests.calculator_api.test_remainder.TestRemainder#test_unsuccessful_remainder_not_int_number", "labels": [{"name": "story", "value": "Вычисление остатка от деления"}, {"name": "epic", "value": "Калькулятор"}, {"name": "feature", "value": "Вычисления калькулятора"}, {"name": "parentSuite", "value": "tests.calculator_api"}, {"name": "suite", "value": "test_remainder"}, {"name": "subSuite", "value": "TestRemainder"}, {"name": "host", "value": "DESKTOP-QQNQKOJ"}, {"name": "thread", "value": "11904-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.calculator_api.test_remainder"}]}