{"name": "test_stop_application", "status": "passed", "steps": [{"name": "Проверка состояния сервера", "status": "broken", "statusDetails": {"message": "httpx.ConnectError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение\n", "trace": "  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\api\\server\\server_api.py\", line 38, in state\n    return self.api_client.get(server_routes_settings.state)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 1054, in get\n    return self.request(\n           ^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\api\\client\\api_client.py\", line 25, in request\n    return super().request(method, url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 827, in request\n    return self.send(request, auth=auth, follow_redirects=follow_redirects)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 914, in send\n    response = self._send_handling_auth(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 942, in _send_handling_auth\n    response = self._send_handling_redirects(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 979, in _send_handling_redirects\n    response = self._send_single_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 1015, in _send_single_request\n    response = transport.handle_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 232, in handle_request\n    with map_httpcore_exceptions():\n  File \"C:\\Users\\Арсений\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\contextlib.py\", line 158, in __exit__\n    self.gen.throw(value)\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 86, in map_httpcore_exceptions\n    raise mapped_exc(message) from exc\n"}, "steps": [{"name": "Отправка \"'GET'\" запроса на \"'/state'\"", "status": "broken", "statusDetails": {"message": "httpx.ConnectError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение\n", "trace": "  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\api\\client\\api_client.py\", line 25, in request\n    return super().request(method, url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 827, in request\n    return self.send(request, auth=auth, follow_redirects=follow_redirects)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 914, in send\n    response = self._send_handling_auth(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 942, in _send_handling_auth\n    response = self._send_handling_redirects(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 979, in _send_handling_redirects\n    response = self._send_single_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_client.py\", line 1015, in _send_single_request\n    response = transport.handle_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 232, in handle_request\n    with map_httpcore_exceptions():\n  File \"C:\\Users\\Арсений\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\contextlib.py\", line 158, in __exit__\n    self.gen.throw(value)\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 86, in map_httpcore_exceptions\n    raise mapped_exc(message) from exc\n"}, "parameters": [{"name": "method", "value": "'GET'"}, {"name": "url", "value": "'/state'"}, {"name": "params", "value": "None"}, {"name": "headers", "value": "None"}, {"name": "cookies", "value": "None"}, {"name": "auth", "value": "<httpx._client.UseClientDefault object at 0x00000276A3624C20>"}, {"name": "follow_redirects", "value": "<httpx._client.UseClientDefault object at 0x00000276A3624C20>"}, {"name": "timeout", "value": "<httpx._client.UseClientDefault object at 0x00000276A3624C20>"}, {"name": "extensions", "value": "None"}], "start": 1723569754519, "stop": 1723569758617}], "start": 1723569754519, "stop": 1723569758617}], "attachments": [{"name": "stdout", "source": "b147c40c-af50-45c8-9a50-3ca4f60c581f-attachment.txt", "type": "text/plain"}], "start": 1723569753535, "stop": 1723569758617, "uuid": "b6120205-1d1e-4e08-9c88-0b6b32baf4b3", "historyId": "7523c939a36c8d05e7019638c59986d0", "testCaseId": "7523c939a36c8d05e7019638c59986d0", "fullName": "tests.application.test_application.TestApplication#test_stop_application", "labels": [{"name": "feature", "value": "Управление приложением из консоли"}, {"name": "story", "value": "Остановка приложение"}, {"name": "epic", "value": "Приложение"}, {"name": "parentSuite", "value": "tests.application"}, {"name": "suite", "value": "test_application"}, {"name": "subSuite", "value": "TestApplication"}, {"name": "host", "value": "DESKTOP-QQNQKOJ"}, {"name": "thread", "value": "11904-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.application.test_application"}]}